"""Generate `version_info.txt`, the Windows version resource embedded in the
executable at build time.

An unsigned executable that carries no version metadata looks anonymous to
antivirus heuristics and is far more likely to be flagged as a false
positive. Embedding real CompanyName / ProductName / FileVersion fields is
one of the cheapest, most effective ways to reduce those false positives.

Run this before PyInstaller (the build scripts and CI already do).
"""
import os

from version import VERSION

HERE = os.path.dirname(os.path.abspath(__file__))

COMPANY = "FolderLens"
PRODUCT = "FolderLens"
DESCRIPTION = "FolderLens - Folder Size Analyzer"
COPYRIGHT = "MIT License - https://github.com/MrHakan/FolderLens"


def _version_tuple(version: str):
    parts = []
    for piece in version.split("."):
        digits = "".join(c for c in piece if c.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


def render(version: str) -> str:
    v = _version_tuple(version)
    vstr = ".".join(str(x) for x in v)
    return f"""# UTF-8
# Auto-generated by make_version_info.py -- do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{COMPANY}'),
         StringStruct('FileDescription', '{DESCRIPTION}'),
         StringStruct('FileVersion', '{vstr}'),
         StringStruct('InternalName', 'FolderLens'),
         StringStruct('LegalCopyright', '{COPYRIGHT}'),
         StringStruct('OriginalFilename', 'FolderLens.exe'),
         StringStruct('ProductName', '{PRODUCT}'),
         StringStruct('ProductVersion', '{vstr}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main():
    out = os.path.join(HERE, "version_info.txt")
    with open(out, "w", encoding="utf-8") as f:
        f.write(render(VERSION))
    print(f"Wrote {out} for version {VERSION}")


if __name__ == "__main__":
    main()
